services:
  - type: web
    name: tiet-policylens
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false
